[build-system]
requires = ["maturin>=0.12"]
build-backend = "maturin"

[project]
name = "rusty_evolution"
version = "0.1.0"
description = "Rust evolution module"
authors = [{ name = "Kouakou Jedidiah Ange-Emmanuel", email = "angemmanuel.kouakou@gmail.com" }]
