apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-runner-role
rules:
  # allow creating & managing batch/v1 Jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "watch", "list", "delete"]
  # allow reading Pods (so it can watch succeed/fail)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-runner-binding
subjects:
  - kind: ServiceAccount
    name: job-runner-sa
    namespace: default
roleRef:
  kind: Role
  name: job-runner-role
  apiGroup: rbac.authorization.k8s.io
